const features = [
  { title: 'D-Balance', desc: 'Topup, pembayaran cepat, cashback, dan riwayat saldo.', href: '/wallet', stat: 'Wallet', accent: '#dfff4f' },
  { title: 'VIP Access', desc: 'Benefit bertingkat, multiplier reward, dan akses premium.', href: '/premium', stat: '4 Tiers', accent: '#f6c453' },
  { title: 'Referral', desc: 'Kode undangan, milestone reward, dan pertumbuhan organik.', href: '/referral', stat: 'Growth', accent: '#75b3e5' },
  { title: 'Affiliate', desc: 'Komisi, tracking conversion, dan campaign partner.', href: '/affiliate', stat: 'Partner', accent: '#35cf72' },
  { title: 'Security', desc: 'Security score, login history, dan proteksi device.', href: '/security', stat: 'Safe', accent: '#ff9f43' },
  { title: 'Reward Vault', desc: 'Coupon reveal, capsule reward, dan daily engagement.', href: '/rewards', stat: 'Reward', accent: '#ff5f68' }
];

export function DlavieMegaSuite() {
  return <section className="relative mx-auto mt-8 max-w-7xl overflow-hidden rounded-[2.25rem] bg-slate-950 p-5 text-white shadow-[0_28px_90px_rgba(15,23,42,.24)] md:p-7"><style jsx global>{`
    .dlavie-feature-card { transform: translateY(0); transition: transform .35s ease, background .35s ease, border-color .35s ease, box-shadow .35s ease; }
    .dlavie-feature-card:hover { transform: translateY(-7px); box-shadow: 0 24px 70px rgba(0,0,0,.25); }
    .dlavie-feature-card:before { content: ''; position: absolute; inset: -1px; border-radius: inherit; opacity: 0; background: radial-gradient(circle at 18% 10%, rgba(223,255,79,.32), transparent 38%), radial-gradient(circle at 90% 70%, rgba(117,179,229,.24), transparent 40%); transition: opacity .35s ease; pointer-events: none; }
    .dlavie-feature-card:hover:before { opacity: 1; }
    .dlavie-suite-pulse { animation: dlavieSuitePulse 7s ease-in-out infinite alternate; }
    .dlavie-suite-line { animation: dlavieSuiteLine 5.5s ease-in-out infinite; }
    @keyframes dlavieSuitePulse { from { transform: translate3d(0,0,0) scale(1); } to { transform: translate3d(-18px,14px,0) scale(1.08); } }
    @keyframes dlavieSuiteLine { 0%,100% { transform: translateX(-45%); opacity: .25; } 50% { transform: translateX(45%); opacity: .9; } }
  `}</style><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#dfff4f]/25 blur-3xl dlavie-suite-pulse" /><div className="pointer-events-none absolute -bottom-28 left-0 h-72 w-72 rounded-full bg-[#75b3e5]/24 blur-3xl dlavie-suite-pulse" /><div className="pointer-events-none absolute left-10 right-10 top-0 h-px bg-gradient-to-r from-transparent via-[#dfff4f] to-transparent dlavie-suite-line" /><div className="relative"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.32em] text-[#dfff4f]">DLAVIE CORE FEATURES</p><h2 className="mt-3 max-w-3xl text-3xl font-black leading-tight tracking-tight md:text-5xl">Infrastruktur commerce digital yang ringkas, aman, dan siap berkembang.</h2><p className="mt-3 max-w-2xl text-sm font-semibold leading-7 text-white/58">Akses fitur utama DLAVIE dari satu dashboard ringan: wallet, VIP, referral, affiliate, keamanan akun, dan reward interaktif.</p></div><a className="rounded-full bg-white px-5 py-3 text-sm font-black text-slate-950 shadow-[0_14px_40px_rgba(255,255,255,.12)] transition hover:-translate-y-1" href="/products">Lihat Produk</a></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{features.map((item, index) => <a key={item.title} href={item.href} className="dlavie-feature-card relative overflow-hidden rounded-[1.45rem] bg-white/[0.065] p-4 ring-1 ring-white/10 backdrop-blur"><div className="relative flex items-start justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[0.22em] text-white/35">0{index + 1} · {item.stat}</p><h3 className="mt-2 text-xl font-black tracking-tight">{item.title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-white/55">{item.desc}</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-slate-950 shadow-[0_0_28px_rgba(255,255,255,.12)]" style={{ background: item.accent }}>↗</span></div></a>)}</div></div></section>;
}
