import { DlavieEcosystemPage } from '@/components/dlavie-ecosystem-page';

const campaigns = [
  { name: 'Premium Drop', clicks: 342, conv: '8.4%', commission: 'Rp 184K' },
  { name: 'Digital Vault', clicks: 219, conv: '5.1%', commission: 'Rp 92K' },
  { name: 'Scratch Coupon', clicks: 511, conv: '11.2%', commission: 'Rp 260K' }
];

export default function AffiliatePage() {
  return <DlavieEcosystemPage eyebrow="VIP AFFILIATE ENGINE" title="Biarkan user ikut menjual DLAVIE." description="Affiliate dashboard untuk tracking klik, konversi, komisi, payout, dan VIP multiplier. Sistem ini membuat user bukan hanya pembeli, tapi partner pertumbuhan." accent="#35cf72" metrics={[{ label: 'Commission', value: 'Rp 536K', hint: 'Preview earned revenue' }, { label: 'Clicks', value: '1.072', hint: 'Tracked affiliate traffic' }, { label: 'Conv.', value: '8.9%', hint: 'Campaign conversion' }, { label: 'VIP Boost', value: '2x', hint: 'Gold+ commission multiplier' }]} actions={[{ label: 'Referral', href: '/referral' }, { label: 'Wallet', href: '/wallet' }, { label: 'Create Link', href: '/login', primary: true }]}><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="dlavie-soft-card overflow-hidden rounded-[2rem] p-6"><p className="text-xs font-black uppercase tracking-[0.28em] text-slate-400">Campaign Performance</p><div className="mt-5 space-y-3">{campaigns.map((c)=><div key={c.name} className="grid grid-cols-4 items-center gap-3 rounded-[1.35rem] bg-white p-4 font-bold shadow-sm"><p className="col-span-1 font-black">{c.name}</p><p>{c.clicks}</p><p>{c.conv}</p><p className="text-right text-green-600">{c.commission}</p></div>)}</div></div><div className="rounded-[2rem] bg-slate-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-[0.28em] text-[#35cf72]">Affiliate Link Generator</p><div className="mt-5 rounded-[1.4rem] bg-white/10 p-4 font-mono text-sm ring-1 ring-white/10">dlavie.com/r/DLV-GOLD128</div><div className="mt-4 grid gap-3"><button className="rounded-full bg-[#35cf72] px-5 py-4 font-black text-slate-950">Copy Link</button><button className="rounded-full bg-white/10 px-5 py-4 font-black ring-1 ring-white/10">Request Payout</button></div><p className="mt-5 text-sm font-semibold leading-7 text-white/55">Komisi masuk ke D-Balance setelah order valid. VIP Gold+ mendapat multiplier otomatis.</p></div></div></DlavieEcosystemPage>;
}
