const features = [
  { title: 'D-Balance', desc: 'Kelola saldo, topup, pembayaran, dan riwayat transaksi.', href: '/wallet', label: 'Wallet', accent: '#dfff4f' },
  { title: 'VIP Access', desc: 'Benefit membership, prioritas fitur, dan akses premium.', href: '/premium', label: 'VIP', accent: '#f6c453' },
  { title: 'Referral', desc: 'Undang pengguna baru dan kelola pertumbuhan komunitas.', href: '/referral', label: 'Referral', accent: '#75b3e5' },
  { title: 'Affiliate', desc: 'Program partner dengan tracking campaign dan komisi.', href: '/affiliate', label: 'Partner', accent: '#35cf72' },
  { title: 'Security', desc: 'Pantau keamanan akun, device session, dan aktivitas login.', href: '/security', label: 'Security', accent: '#ff9f43' },
  { title: 'Reward Vault', desc: 'Reward interaktif, coupon reveal, dan engagement pengguna.', href: '/rewards', label: 'Reward', accent: '#ff5f68' }
];

export function DlavieMegaSuite() {
  return <section className="relative mx-auto mt-7 max-w-7xl overflow-hidden rounded-[2.1rem] bg-slate-950 p-4 text-white shadow-[0_24px_80px_rgba(15,23,42,.22)] md:p-5"><style dangerouslySetInnerHTML={{__html: `
    .dlavie-feature-slider { scroll-snap-type: x mandatory; }
    .dlavie-feature-slide { scroll-snap-align: start; transition: transform .35s ease, box-shadow .35s ease, background .35s ease; }
    .dlavie-feature-slide:hover { transform: translateY(-7px) rotate(-.35deg); box-shadow: 0 24px 70px rgba(0,0,0,.26); }
    .dlavie-feature-slide:before { content: ''; position: absolute; inset: 0; border-radius: inherit; opacity: 0; background: radial-gradient(circle at 14% 10%, rgba(255,255,255,.34), transparent 34%), radial-gradient(circle at 92% 82%, rgba(223,255,79,.22), transparent 38%); transition: opacity .35s ease; pointer-events: none; }
    .dlavie-feature-slide:hover:before { opacity: 1; }
    .dlavie-slider-shine { animation: dlavieSliderShine 5.5s ease-in-out infinite; }
    .dlavie-slider-orb { animation: dlavieSliderOrb 7s ease-in-out infinite alternate; }
    @keyframes dlavieSliderShine { 0%,100% { transform: translateX(-38%); opacity: .2; } 50% { transform: translateX(38%); opacity: .85; } }
    @keyframes dlavieSliderOrb { from { transform: translate3d(0,0,0) scale(1); } to { transform: translate3d(-16px,12px,0) scale(1.08); } }
  `}} /><div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[#dfff4f]/24 blur-3xl dlavie-slider-orb" /><div className="pointer-events-none absolute -bottom-24 left-8 h-64 w-64 rounded-full bg-[#75b3e5]/22 blur-3xl dlavie-slider-orb" /><div className="pointer-events-none absolute left-8 right-8 top-0 h-px bg-gradient-to-r from-transparent via-[#dfff4f] to-transparent dlavie-slider-shine" /><div className="relative"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.28em] text-[#dfff4f]">DLAVIE SYSTEMS</p><h2 className="mt-2 text-2xl font-black tracking-tight md:text-3xl">Fitur utama dalam satu akses cepat.</h2><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-white/55">Geser card untuk membuka fitur DLAVIE tanpa membuat homepage terlalu panjang.</p></div><a className="hidden rounded-full bg-white px-4 py-3 text-sm font-black text-slate-950 transition hover:-translate-y-1 md:inline-flex" href="/products">Products</a></div><div className="dlavie-feature-slider dlavie-x-scroll mt-5 flex gap-3 overflow-x-auto pb-2"><a href="/premium" className="dlavie-feature-slide relative min-w-[82%] overflow-hidden rounded-[1.8rem] bg-gradient-to-br from-[#fff4c2] via-white to-[#f6c453] p-5 text-slate-950 ring-1 ring-white/20 sm:min-w-[410px]"><div className="relative"><p className="text-xs font-black uppercase tracking-[0.24em] text-amber-700">Featured Access</p><h3 className="mt-3 text-3xl font-black tracking-tight">VIP Access</h3><p className="mt-2 max-w-sm text-sm font-bold leading-6 text-slate-600">Pusat membership untuk benefit premium, prioritas fitur, dan pengalaman akun yang lebih eksklusif.</p><span className="mt-5 inline-flex rounded-full bg-slate-950 px-4 py-3 text-sm font-black text-[#ffe58a]">Open VIP →</span></div></a>{features.filter((item) => item.title !== 'VIP Access').map((item) => <a key={item.title} href={item.href} className="dlavie-feature-slide relative min-w-[72%] overflow-hidden rounded-[1.8rem] bg-white/[0.07] p-5 ring-1 ring-white/10 backdrop-blur sm:min-w-[320px]"><div className="relative flex h-full min-h-[190px] flex-col justify-between"><div><div className="flex items-center justify-between gap-3"><p className="text-xs font-black uppercase tracking-[0.24em] text-white/38">{item.label}</p><span className="h-3 w-3 rounded-full shadow-[0_0_24px_rgba(255,255,255,.2)]" style={{ background: item.accent }} /></div><h3 className="mt-4 text-2xl font-black tracking-tight">{item.title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-white/55">{item.desc}</p></div><span className="mt-5 inline-flex rounded-full bg-white/10 px-4 py-2 text-sm font-black ring-1 ring-white/10">Open →</span></div></a>)}</div></div></section>;
}
