import { useEffect, useMemo, useState, type CSSProperties, type MouseEvent } from 'react';
import { createSupabaseBrowserClient } from '@/lib/supabase-client';
import s from './ppob-reactbits.module.css';

type Product = { id:string; sku_code:string; product_name:string; category:string; brand?:string|null; selling_price:number };
type Category = { key:string; label:string; count:number; color:string; second:string; kind:string };
const rupiah=(v=0)=>`Rp ${Number(v||0).toLocaleString('id-ID')}`;
const clean=(v?:string|null,f='Digital')=>String(v||f).trim()||f;
const css=(v:Record<string,string|number>)=>v as CSSProperties;
function catLabel(c:string){const v=clean(c),t=v.toLowerCase(); if(t.includes('aigo'))return'Axis AIGO'; if(t.includes('always'))return'TRI AlwaysOn'; if(t.includes('internet'))return'Paket Data'; return v;}
function catTheme(label:string){const t=label.toLowerCase(); if(t.includes('game')||t.includes('stream'))return{color:'#ff7a18',second:'#ffe100',kind:'game'}; if(t.includes('pln')||t.includes('listrik'))return{color:'#ffd400',second:'#00c2ff',kind:'pln'}; if(t.includes('data')||t.includes('aigo')||t.includes('always'))return{color:'#30d5ff',second:'#8b5cf6',kind:'data'}; if(t.includes('pulsa'))return{color:'#dfff4f',second:'#35f29b',kind:'phone'}; if(t.includes('voucher'))return{color:'#b58cff',second:'#ff6bd6',kind:'voucher'}; return{color:'#dfff4f',second:'#30d5ff',kind:'spark'};}
function brandTheme(b?:string|null){const k=clean(b).toLowerCase().replace(/[^a-z0-9]+/g,''); if(k.includes('smartfren'))return{a:'#ff174d',b:'#ffffff',c:'#2a0611',name:'SMARTFREN'}; if(k.includes('telkomsel')||k.includes('tsel'))return{a:'#ff174d',b:'#ffb703',c:'#300711',name:'TELKOMSEL'}; if(k.includes('axis'))return{a:'#7b2cff',b:'#ffea00',c:'#170a34',name:'AXIS'}; if(k.includes('xl'))return{a:'#1746ff',b:'#30d5ff',c:'#071342',name:'XL'}; if(k.includes('tri')||k.includes('three'))return{a:'#0b0b0d',b:'#ff6b00',c:'#050506',name:'TRI'}; if(k.includes('indosat')||k.includes('isat'))return{a:'#ffd400',b:'#e51b23',c:'#302400',name:'INDOSAT'}; if(k.includes('pln'))return{a:'#00a8ff',b:'#ffd400',c:'#062235',name:'PLN'}; return{a:'#dfff4f',b:'#30d5ff',c:'#101522',name:clean(b,'DLAVIE').toUpperCase().slice(0,12)};}
function placeholder(p?:Product|null){const t=`${p?.category||''} ${p?.brand||''} ${p?.product_name||''}`.toLowerCase(); if(t.includes('game')||t.includes('free fire')||t.includes('mobile legends'))return'User ID / Server ID'; if(t.includes('pln')||t.includes('token'))return'Nomor meter / ID pelanggan PLN'; return'Nomor HP tujuan';}
function spot(e:MouseEvent<HTMLElement>){const r=e.currentTarget.getBoundingClientRect(); e.currentTarget.style.setProperty('--mx',`${e.clientX-r.left}px`); e.currentTarget.style.setProperty('--my',`${e.clientY-r.top}px`);}

export function PpobReactBits(){
 const[products,setProducts]=useState<Product[]>([]),[status,setStatus]=useState('Loading live packs...'),[query,setQuery]=useState(''),[active,setActive]=useState(''),[brand,setBrand]=useState('all'),[selected,setSelected]=useState<Product|null>(null),[target,setTarget]=useState(''),[token,setToken]=useState(''),[orderStatus,setOrderStatus]=useState(''),[ordering,setOrdering]=useState(false);
 useEffect(()=>{fetch('/api/ppob-products').then(r=>r.json()).then(j=>{const list=Array.isArray(j.products)?j.products:[];setProducts(list);setStatus(list.length?'VIPayment live catalog connected.':'No active provider products yet.')}).catch(()=>setStatus('Catalog failed to load. Refresh this page.')); const supabase=createSupabaseBrowserClient(); supabase.auth.getSession().then(({data})=>setToken(data.session?.access_token||'')).catch(()=>setToken(''));},[]);
 const categories=useMemo<Category[]>(()=>{const m=new Map<string,number>(); products.forEach(p=>m.set(catLabel(p.category),(m.get(catLabel(p.category))||0)+1)); return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]).map(([label,count])=>({key:label,label,count,...catTheme(label)}));},[products]);
 const brands=useMemo(()=>{const set=new Set<string>(); products.forEach(p=>{if(active&&catLabel(p.category)!==active)return; set.add(clean(p.brand));}); return ['all',...Array.from(set).sort((a,b)=>a.localeCompare(b))].slice(0,24);},[products,active]);
 useEffect(()=>setBrand('all'),[active]);
 const visible=useMemo(()=>{const q=query.toLowerCase().trim(); return products.filter(p=>{const c=catLabel(p.category),b=clean(p.brand); const h=`${p.product_name} ${b} ${c} ${p.sku_code}`.toLowerCase(); if(active&&c!==active)return false; if(brand!=='all'&&b!==brand)return false; if(q&&!h.includes(q))return false; return true;});},[products,active,brand,query]);
 const overview=!active&&!query.trim(); const activeTheme=active?catTheme(active):{color:'#dfff4f',second:'#30d5ff',kind:'spark'}; const heroProduct=visible[0]||products[0];
 const reset=()=>{setActive('');setBrand('all');setQuery('')};
 const manualMessage=()=>!selected?'':encodeURIComponent(`Halo admin Dlavie, saya ingin order PPOB:\n\nProduk: ${selected.product_name}\nKode: ${selected.sku_code}\nTujuan: ${target||'-'}\nHarga: ${rupiah(selected.selling_price)}\n\nMohon dibantu prosesnya.`);
 async function submitOrder(){ if(!selected||!target.trim())return; if(!token){setOrderStatus('Kamu belum login. Login untuk memakai D-Balance, atau pakai order manual dulu.');return} setOrdering(true);setOrderStatus('Creating automatic D-Balance order...'); try{const res=await fetch('/api/ppob-order',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({product_id:selected.id,customer_no:target.trim()})}); const json=await res.json().catch(()=>({})); if(!res.ok){setOrderStatus(json.error||'Order otomatis belum bisa diproses. Kamu bisa lanjut manual dulu.');return} setOrderStatus(`Order berhasil dibuat. Ref: ${json.order?.ref_id||'-'}. Cek Orders/Wallet untuk status.`)}catch{setOrderStatus('Koneksi order gagal. Kamu bisa lanjut manual dulu.')}finally{setOrdering(false)}}
 return <main className={s.page}><div className={s.grid}/><div className={s.aurora}/><div className={s.noise}/><section className={s.shell}><header className={s.top}><div className={s.brand}><div className={s.logo}><Logo/></div><div><p className={s.brandTitle}>Dlavie PPOB</p><p className={s.brandSub}>ReactBits-style category experience</p></div></div><div className={s.actions}><input className={s.input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search inside packs..."/><button className={s.ghost} onClick={reset}>Categories</button><a className={s.primary} href="/wallet">Wallet</a></div></header><div className={s.layout}><aside className={s.side}><p className={s.sideLabel}>Collections</p><div className={s.sideList}><Side active={!active} color="#dfff4f" label="Overview" count={categories.length} kind="spark" onClick={reset}/>{categories.map(c=><Side key={c.key} active={active===c.key} color={c.color} label={c.label} count={c.count} kind={c.kind} onClick={()=>setActive(c.key)}/>)}</div></aside><section className={s.content}><div className={s.chipRow}><button className={`${s.chip} ${!active?s.chipActive:''}`} onClick={reset}><Icon kind="spark" color={!active?'#050506':'#dfff4f'} micro/>Overview</button>{categories.map(c=><button key={c.key} className={`${s.chip} ${active===c.key?s.chipActive:''}`} onClick={()=>setActive(c.key)}><Icon kind={c.kind} color={active===c.key?'#050506':c.color} micro/>{c.label}</button>)}</div><Hero active={active} status={status} activeTheme={activeTheme} heroProduct={heroProduct} categories={categories.length} shown={overview?categories.length:visible.length}/>{overview?<div className={s.cardGrid}>{categories.map((c,i)=><CategoryBox key={c.key} c={c} i={i} onClick={()=>setActive(c.key)}/>)}</div>:<><div className={s.brandRow}>{brands.map(b=><button key={b} className={`${s.chip} ${brand===b?s.chipActive:''}`} onClick={()=>setBrand(b)}>{b==='all'?'All Brands':b}</button>)}</div><div className={s.cardGrid}>{visible.map((p,i)=><ProductBox key={p.id} p={p} i={i} onClick={()=>{setSelected(p);setTarget('');setOrderStatus('')}}/>)}</div>{!visible.length&&<Empty/>}</>}</section></div></section>{selected&&<Drawer selected={selected} target={target} setTarget={setTarget} close={()=>setSelected(null)} submit={submitOrder} ordering={ordering} orderStatus={orderStatus} manualMessage={manualMessage}/>}</main>;
}
function Side({active,color,label,count,kind,onClick}:{active:boolean;color:string;label:string;count:number;kind:string;onClick:()=>void}){return <button className={`${s.sideBtn} ${active?s.sideBtnActive:''}`} style={css({'--tone':color})} onClick={onClick}><span className={s.sideText}><Icon kind={kind} color={color} micro/><span className={s.sideName}>{label}</span></span><span className={s.sideCount}>{count}</span></button>}
function Hero({active,status,activeTheme,heroProduct,categories,shown}:{active:string;status:string;activeTheme:any;heroProduct?:Product;categories:number;shown:number}){return <div className={s.hero} style={css({'--accent':activeTheme.color})}><div className={s.heroInner}><div><div className={s.badges}><span className={`${s.badge} ${s.badgeAccent}`}>{active?'Collection Open':'Choose Collection'}</span><span className={s.badge}>{status}</span></div><h1 className={s.title}>{active?`${active} packs`:'Select a category box first.'}</h1><p className={s.desc}>Tidak ada lagi daftar produk panjang di awal. Pilih collection box, lalu produk dalam kategori itu muncul sebagai interactive component cards.</p></div><div className={s.previewWrap}><div className={`${s.preview} ${s.heroPreview}`} style={css({'--lineA':activeTheme.color,'--lineB':activeTheme.second})}><BrandVisual product={heroProduct} kind={activeTheme.kind}/></div><div className={s.stats}><Stat label="Categories" value={categories}/><Stat label="Shown" value={shown}/><Stat label="Provider" value="VIP"/></div></div></div></div>}
function CategoryBox({c,i,onClick}:{c:Category;i:number;onClick:()=>void}){return <button onMouseMove={spot} onClick={onClick} className={`${s.card} ${s.categoryCard}`} style={css({'--spot':`${c.color}33`,'--lineA':c.color,'--lineB':c.second,animationDelay:`${Math.min(i,14)*34}ms`})}><div className={`${s.preview} ${s.categoryPreview}`} style={css({'--lineA':c.color,'--lineB':c.second})}><CategoryVisual c={c}/></div><div className={s.cardBody}><div className={s.cardTop}><h3 className={s.cardTitle}>{c.label}</h3><span className={s.pill}>{c.count}</span></div><p className={s.smallText}>Open this collection to view only its live product components.</p><div className={s.divider}><span className={s.kicker}>Open collection</span><span className={s.arrow}>↗</span></div></div></button>}
function ProductBox({p,i,onClick}:{p:Product;i:number;onClick:()=>void}){const b=brandTheme(p.brand),t=catTheme(catLabel(p.category)); return <button onMouseMove={spot} onClick={onClick} className={s.card} style={css({'--spot':`${b.a}30`,'--lineA':b.a,'--lineB':b.b,animationDelay:`${Math.min(i,18)*22}ms`})}><div className={`${s.preview} ${s.productPreview}`} style={css({'--lineA':b.a,'--lineB':b.b})}><BrandVisual product={p} kind={t.kind}/><div style={{position:'absolute',right:12,top:12,borderRadius:999,background:'rgba(0,0,0,.75)',padding:'6px 10px',fontSize:11,fontWeight:950,color:b.b}}>{rupiah(p.selling_price)}</div></div><div className={s.cardBody}><div className={s.cardTop}><span className={s.tag} style={{color:t.color}}><Icon kind={t.kind} color={t.color} micro/><span className={s.truncate}>{catLabel(p.category)}</span></span><span className={s.pill}>{p.sku_code}</span></div><h3 className={s.productTitle}>{p.product_name}</h3><div className={s.divider}><span className={s.smallText}>{b.name} component</span><span className={s.arrow}>↗</span></div></div></button>}
function Drawer({selected,target,setTarget,close,submit,ordering,orderStatus,manualMessage}:{selected:Product;target:string;setTarget:(v:string)=>void;close:()=>void;submit:()=>void;ordering:boolean;orderStatus:string;manualMessage:()=>string}){const b=brandTheme(selected.brand),t=catTheme(catLabel(selected.category));return <div className={s.modalBack}><section className={s.modal}><div className={s.modalHead} style={{background:`linear-gradient(135deg,${b.c},#050507 66%)`}}><div className={s.modalArt}><BrandVisual product={selected} kind={t.kind}/></div><button className={s.closeBtn} onClick={close}>Tutup</button><div className={s.modalTitle}><p className={s.modalEyebrow} style={{color:b.b}}>Open Product</p><h2 className={s.modalName}>{selected.product_name}</h2><p className={s.modalMeta}>{catLabel(selected.category)} · {selected.brand||'Digital'} · {selected.sku_code}</p></div><div className={s.priceBox}><p className={s.modalMeta}>Total Bayar</p><p style={{marginTop:4,fontSize:38,fontWeight:1000,color:b.b}}>{rupiah(selected.selling_price)}</p></div></div><div className={s.modalBody}><label className={s.label}>Nomor tujuan / User ID</label><input className={s.input} value={target} onChange={e=>setTarget(e.target.value)} placeholder={placeholder(selected)}/><div className={s.notice}><b style={{color:'#dfff4f'}}>D-Balance Checkout</b><br/>Order otomatis memakai D-Balance dan VIPayment. Kalau belum login atau saldo kurang, gunakan order manual.</div>{orderStatus&&<p className={s.notice} style={{background:'#fff',color:'#000'}}>{orderStatus}</p>}<div className={s.modalActions}><button className={s.ghost} onClick={close}>Pilih Lain</button><button className={target.trim()&&!ordering?s.primary:s.ghost} onClick={submit} disabled={!target.trim()||ordering}>{ordering?'Memproses...':'Lanjut Order'}</button></div><a className={s.manual} href={`https://wa.me/?text=${manualMessage()}`}>Order Manual via WhatsApp</a></div></section></div>}
function Stat({label,value}:{label:string;value:number|string}){return <div className={s.stat}><p className={s.statLabel}>{label}</p><p className={s.statValue}>{value}</p></div>}
function Empty(){return <div className={s.previewWrap} style={{marginTop:20,padding:40,textAlign:'center'}}><Icon kind="spark" color="#dfff4f"/><h2 className={s.cardTitle}>No matching pack</h2><p className={s.smallText}>Ganti brand, kategori, atau kata pencarian.</p></div>}
function Logo(){return <svg viewBox="0 0 48 48" width="20" height="20" fill="none"><path d="M11 8h14c8 0 13 6 13 16S33 40 25 40H11V8Z" stroke="currentColor" strokeWidth="5"/><path d="M21 18h4c3 0 5 2 5 6s-2 6-5 6h-4V18Z" fill="currentColor"/></svg>}
function Icon({kind,color,micro}:{kind:string;color:string;micro?:boolean}){const size=micro?14:34,common={width:size,height:size,viewBox:'0 0 48 48',fill:'none',className:'svg-icon'}; if(kind==='data')return <svg {...common}><path d="M8 31c8.8-8.7 23.2-8.7 32 0" stroke={color} strokeWidth="4" strokeLinecap="round"/><path d="M15 38c5-4.8 13-4.8 18 0" stroke={color} strokeWidth="4" strokeLinecap="round"/><circle cx="24" cy="42" r="3" fill={color}/></svg>; if(kind==='game')return <svg {...common}><rect x="6" y="15" width="36" height="22" rx="10" stroke={color} strokeWidth="4"/><path d="M16 26h8M20 22v8" stroke={color} strokeWidth="3" strokeLinecap="round"/><circle cx="31" cy="25" r="2.5" fill={color}/><circle cx="36" cy="29" r="2.5" fill={color}/></svg>; if(kind==='pln')return <svg {...common}><path d="M28 4 11 27h12l-3 17 18-24H26l2-16Z" fill={color}/></svg>; if(kind==='phone')return <svg {...common}><rect x="14" y="5" width="20" height="38" rx="6" stroke={color} strokeWidth="4"/><path d="M21 10h6M22 36h4" stroke={color} strokeWidth="3" strokeLinecap="round"/></svg>; return <svg {...common}><path d="M24 5v38M5 24h38M10 10l28 28M38 10 10 38" stroke={color} strokeWidth="4" strokeLinecap="round"/><circle cx="24" cy="24" r="7" fill={color}/></svg>}
function CategoryVisual({c}:{c:Category}){return <svg viewBox="0 0 420 180" className="h-full w-full" preserveAspectRatio="xMidYMid slice"><rect width="420" height="180" rx="24" fill="#050506" opacity=".12"/><circle cx="342" cy="38" r="95" fill={c.color} opacity=".62"/><circle cx="56" cy="158" r="105" fill={c.second} opacity=".32"/><path d="M0 128 C70 82 140 198 224 116 C292 50 342 84 420 42 V180 H0Z" fill="rgba(255,255,255,.18)"/><foreignObject x="154" y="36" width="112" height="112"><div style={{height:'112px',display:'grid',placeItems:'center',borderRadius:30,background:'rgba(0,0,0,.72)'}}><Icon kind={c.kind} color={c.second}/></div></foreignObject></svg>}
function BrandVisual({product,kind}:{product?:Product;kind:string}){const b=brandTheme(product?.brand);return <svg viewBox="0 0 420 220" className="h-full w-full" preserveAspectRatio="xMidYMid slice"><rect width="420" height="220" rx="30" fill={b.c}/><circle cx="344" cy="48" r="105" fill={b.a} opacity=".72"/><circle cx="64" cy="188" r="115" fill={b.b} opacity=".34"/><path d="M0 166 C74 102 135 238 237 138 C312 64 354 88 420 50 V220 H0Z" fill="rgba(255,255,255,.20)"/><rect x="32" y="42" width="108" height="138" rx="24" fill="#050507" opacity=".94"/><rect x="44" y="56" width="84" height="96" rx="16" fill="rgba(255,255,255,.12)"/><rect x="56" y="70" width="58" height="10" rx="5" fill={b.a}/><rect x="56" y="90" width="42" height="8" rx="4" fill={b.b}/><circle cx="86" cy="166" r="5" fill="#fff" opacity=".7"/><rect x="250" y="45" width="124" height="102" rx="22" fill="rgba(255,255,255,.86)"/><rect x="264" y="61" width="60" height="12" rx="6" fill={b.a}/><rect x="264" y="85" width="94" height="10" rx="5" fill="#050507" opacity=".18"/><rect x="264" y="106" width="72" height="10" rx="5" fill="#050507" opacity=".16"/><circle cx="183" cy="147" r="25" fill="#050507" opacity=".92"/><foreignObject x="162" y="126" width="42" height="42"><div style={{height:'42px',display:'grid',placeItems:'center'}}><Icon kind={kind} color={b.b}/></div></foreignObject><text x="165" y="75" fill="#fff" fontSize="27" fontWeight="900" fontFamily="Arial, sans-serif" letterSpacing="1.5">{b.name}</text><text x="166" y="101" fill="rgba(255,255,255,.7)" fontSize="12" fontWeight="800" fontFamily="Arial, sans-serif">{catLabel(product?.category||'Digital').toUpperCase()}</text></svg>}
